# About Our Solar System

import time

print("Hello there Astronomer, nice to see you")
time.sleep(1)
print("Today we will learn about our solar system")
time.sleep(1)
print("Our solar system consisted of 9 planets until 2006 when International Astronomical Union (IAU) declared it was a dwarf planet")
time.sleep(2)
print("You might think what is a dwarf planet?")
time.sleep(2)
print("Think about it yourself for sometime...")
time.sleep(7)
print("A dwarf planet is a small planetary-mass object that is in direct orbit around the Sun")
time.sleep(2)
print("Dwarf planets are usually smaller than other planets")
time.sleep(2)
print("There are 8 planets in our solar system now")
time.sleep(2)
print("1. Mercury")
time.sleep(2)
print("Mercury is the closest planet to the Sun ")
time.sleep(2)
print("It is the smallest planet in our solar system")
time.sleep(2)
print("It experiences extreme temperatures")
time.sleep(2)
print("Which lowers to -180`C and highs to 430`C.")
time.sleep(2)
print("2. Venus")
time.sleep(2)
print("Venus also known as Earth's sister Planet is the second planet from the sun")
time.sleep(2)
print("Despite being the second planet from sun it is the hottest planet in our solar system!")
time.sleep(2)
print("Venus has very thick atmosphere because of which it is the hottest plantet in our solar system.")
time.sleep(2)
print("A day in venus is longer than earth's 1 year")
