# American Revolution

name = input("Enter your name: ")

import time

print(f"Hello there {name}, Today you will learn about American Revolution")
time.sleep(2)
print("American Revolution also known as the American War of Independence was from 1775-1783")
time.sleep(2)
print("So when Christopher Columbus discovered America in 1492, people from Europe started settling in the newly founded country")
time.sleep(2)
print("Within a short period of time these people began to form small colonies and settled in America from about 16th Century onwards.")
time.sleep(2)
print("By the middle of 18th Century, there were around 13 British Colonies who came from England seeking money, freedom and a better life.")
time.sleep(2)
print("The governement of these 13 colonies were run by an elected body")
time.sleep(2)
print("They were free to manage their own administration but the trade and economic factors were controlled by the British governement")
time.sleep(2)
print("Every colony had a governor and a local council, who resided in the colonies in which they were elected")
time.sleep(2)
print("In a passage of time the 13 colonies developed and started considering America as their own country.")
time.sleep(2)
print("They began to demand for self control for their country from the British")
time.sleep(2)
print("British government on the other hand thought that it had established colonies for their own benefit and it was necessary to keep them under control")
time.sleep(2)
print("The American War of Independence was mainly fought between the 13 colonies in order to free themselves")
time.sleep(2)
print("The American War of Independence was fought from April 19, 1775 to September 3, 1783 and resulted in the independence of America")
time.sleep(2)
print("Lets come to the Main Causes of American Revolution but first let me ask you some questions")
time.sleep(2)
answer1 = input("From when was American War of Independence fought? ")
answer2 = input("How many colonies were settled in America? ")

if answer1 == "April 19, 1775" or "1775":
    print("The answer is correct!")
else:
    print("The answer is wrong")

if answer2 == "13" or "thirteen":
    print("Answer is correct!")
else:
    print("Answer is incorrect")
    
print("Okay let's come to the main reasons for American Revolution")
time.sleep(2)
print("The Economic Restrictions")
time.sleep(1)
print("Britain had introduced a number of restrictions on American business and commerce.")
time.sleep(2)
print("All the trading activities wherer industrial, economic, and ecen westward expansion were strictly controlled by Britain.")
time.sleep(3)
print("The Molasses Act")
time.sleep(1)
print("The Molasses Act of March 1773 as an act of the parliaent of Great Britain")
time.sleep(2)
print("They levied a duty of about six pence a gallon on the Molasses brought from France and Spain to West Indies and the American colonies.")
time.sleep(3)
print("Navigation Act")
time.sleep(2)
print("Navigation Act was mainly passed by British Parliament in 1651 for the purpose of carrying on colonial trade in British ships")
time.sleep(2)
print("Stamp Act")
time.sleep(2)
print("This Act of 1765 made it compulsary to affix stamp on every document.")
time.sleep(2)
print("This act increased duty on all newspapers, legal and commercial documents and imposed stamp taxes in all business and legal transactions in America")
time.sleep(2)
print("Boston Tea Party")
time.sleep(2)
print("The Prime Minister of Britain decided to allow the agents of the East India Company to sell tea directly to the colonists.")
time.sleep(2)
print("Several colonies refused to unload the tea that came from Britain")
time.sleep(2)
print("Boston Governor Hutchinson ordered to unload the tea, at night a group of Red Indians, boarded the ships and threw away the tea boxes into the sea")
time.sleep(2)
print("This incident is known as Boston Tea Party")
