# Language of Chemistry

import time

name = input("Hello there, enter your name: ")

print(f"Hello {name}, Today you will learn about the Language of Chemistry")
print("Firstly you may ask what is Chemistry actually?")
time.sleep(2)
print("What do you think chemistry is?")
input()
time.sleep(2)
print("Chemistry is the branch of science which deals with the study of chemicals")
time.sleep(2)
print("Now the Language of Chemistry means the equations and the reactions of the chemicals")
time.sleep(2)
print("Language of chemistry for some people it may be hard and some people it may be easy")
time.sleep(2)
print("Here are some Chemicals with their formula \n")
time.sleep(2)
print("Sodium - Na")
time.sleep(2)
print("Carbon - C")
time.sleep(2)
print("Hydrogen - H")
time.sleep(2)
print("Gold - Au")
time.sleep(2)
print("Silver - Ag")
time.sleep(2)
print("And many more...")
time.sleep(3)
print("Everything around us is made up of atoms")
time.sleep(2)
print("Here are some definitions you should know")
time.sleep(2)
print("Valency")
time.sleep(1)
print("The combining capacity of an element is known as its valency")
time.sleep(2)
print("Radical")
time.sleep(1)
print("A positively or negatively charged compomemt of a compoumd consisting of a single atom or groups of atom.")
time.sleep(3)
print("Chemical Formula")
time.sleep(1)
print("A chemical formula is a symbolic representation of a molecule of a compound it denotes the number of atoms of each element present in a compound")
time.sleep(4)
print("Chemical Reaction")
time.sleep(1)
print("A chemical reaction is described by a chemical equation. The equation gives identities and quantities of the substances involved in a reaction")
time.sleep(5)
print("Let me tell you about some chemical equations")
time.sleep(2)
print("CO + O2 ----> CO2")
time.sleep(0.5)
print("H2 + O2 -----> H2O")
time.sleep(2)
print("The things written on the left side are called Reactants")
time.sleep(1)
print("The things written on right are known as the products")
