# A Story game!
import time

def second_choice():
  choice2 = input("Where do you want to go (left/right): ")
  if choice2 == "left":
    left_safe()
  elif choice2 == "right":
    right_safe()
  else:
    print("Invalid choice choose again (left/right): ")
    second_choice()

def left_safe():
  print("You are going to left safe...")
  time.sleep(2)
  print("You get poked with something on your foot")
  time.sleep(2)
  print("'What is it?' you ask yourself")
  time.sleep(2)
  print("You remove your foot and see a key! You pick it up and put it in your pocket")
  time.sleep(2)
  print("You continue walking to the safe..")
  time.sleep(2)
  print("You see a note on the safe")
  time.sleep(2)
  print("It says...")
  time.sleep(2)
  print("'The safe is locked with a code...'")
  time.sleep(2)
  print("You try to find the code..")
  time.sleep(2)
  print("Then you suddenly remember something...")
  time.sleep(2)
  remember()
  print("You put the code and it opens!")
  time.sleep(2)
  print("'Guess what is it?', you ask yourself")
  time.sleep(2)
  print("Its...")
  time.sleep(2)
  print("Itss!......")
  time.sleep(2)
  print("THERE ARE GOLD BARS!!")
  time.sleep(2)
  print("You are going to be rich!!")
  time.sleep(2)
  print("You go home and live the rest of your life with the gold bars")

def right_safe():
  print("You go near the right safe...")
  time.sleep(2)
  print("You see a note saying, 'You need a key to open this safe'")
  time.sleep(2)
  print("You say, 'Ahh, I don't know where is the key!")
  time.sleep(2)
  print("You try to move the safe but nothing is there!")
  time.sleep(2)
  print("Suddenly, something reflects into your eyes 'Its Shiny'")
  time.sleep(2)
  print("You go near it")
  time.sleep(2)
  print("It's..")
  time.sleep(2)
  print("It's a key!")
  time.sleep(2)
  print("You pick the key and go to the safe again")
  time.sleep(2)
  print("You open the safe and see a note saying..")
  time.sleep(2)
  print("'LEAVE ARCADE FOR SOMETIME AND TOUCH GRASS BRO!!!'")
  
def remember():
  memory = input("Do you remember it? (yes/no): ").lower()
  if memory == "yes":
    memory2 = input("What is it?(in one word): ").lower()
    if memory2 == "note":
      print("You got it!")
    else:
      print("oops! try again")
      remember()
  else:
    print("No its not that!")
    print("try again!")
    remember()

def left_room():
  print("You enter the left room. You see something shiny in the dark...")
  time.sleep(2)
  print("You see a glass bottle... You think its just a waste ")
  time.sleep(2)
  print("Wait it has something inside!")
  time.sleep(2)
  print("You open the bottle and see a..")
  time.sleep(2)
  print("PAPERRR!!!")
  time.sleep(2)
  print("You say its just a waste of time again")
  time.sleep(2)
  print("As you were about to tear the paper, you see a note written on it")
  time.sleep(2)
  print("It says something...")
  time.sleep(2)
  print("But what is it?")
  time.sleep(2)
  print("You say 'It has some numbers on it but what does it mean?'")
  time.sleep(2)
  print("The numbers written are..")
  time.sleep(2)
  print("84433777330444777707777666633844.44466404446608443304466688777733")
  time.sleep(2)
  print("You saw one more paper in the bottle..")
  time.sleep(2)
  print("You take it out see something written")
  time.sleep(2)
  print("It says..")
  time.sleep(2)
  print(" 2 = a,b,c 3 = d,e,f 4 = g,h,i 5 = j,k,l")
  print(" 6 = m,n,o 7 = p,q,r,s 8 = t,u,v 9 = w,x,y,z")
  print(" . = ignore 0 = 'space'")
  decode = input("Try to decode it: ").lower()
  
  def decode():
    if decode == "there is something in this house":
      print("You say 'There is something in this house'")
    else:
      print("Try to decode it again")
      decode()
  print("You come out of the room")  
  print("You see a safe to your right and another safe to the left")
  second_choice()

def right_room():
  print("You enter the right room. You get poked by something in your feet")
  time.sleep(2)
  print("You remove your foot and see a..")
  time.sleep(2)
  print("Key!!")
  time.sleep(2)
  print("'There is also something attached to it' you say")
  time.sleep(2)
  print("There is a note on it, written...")
  time.sleep(2)
  print("Key to the paradise")
  time.sleep(2)
  print("You say, 'Interesting...'")
  time.sleep(2)
  print("'I wonder where will I use it'")
  time.sleep(2)
  print("You try to search more in the room")
  time.sleep(2)
  print("You see a painting of Mona Lisa")
  time.sleep(2)
  print("'Looks like nothing's here' you say")
  time.sleep(2)
  print("As you about to go towards the door..")
  time.sleep(2)
  print("The painting falls! ")
  time.sleep(2)
  print("'Is something there?', you say 'Looks like a lever'")
  time.sleep(2)
  print("You pull the lever and something falls on your head")
  time.sleep(2)
  print("Its a small box")
  time.sleep(2)
  print("You open it and see a..")
  time.sleep(2)
  print("piece of gold")
  time.sleep(2)
  print("'Wow Gold!!'")
  time.sleep(2)
  print("You come out of the room")
  time.sleep(5)
  print("You wake up in your bed 💀")

  
def first_choice():
  choice = input("Which way you want to go? (left/right): ").lower()
  if choice == "left":
    left_room()
  elif choice == "right":
    right_room()
  else:
    print("Invalid choice. Please try again.")
    first_choice()

def startGame():
  print("Welcome to the Treasury!")
  print("You find yourself in a dark room. There are doors going left and right.")
  first_choice()

startGame()

